### ISSUE TITLE
A few minor changes

### ISSUE THREAD

**Issue by dryairship** [maneeshpm/IITKBucks-Assignments#1]
In your verifier file, change `pss` to `PKCS1_PSS`.

Thus, change:

`from Crypto.Signature import pss`  
to  
`from Crypto.Signature import PKCS1_PSS`

and 

`varifier = pss.new(publicKey)`  
to  
`varifier = PKCS1_PSS.new(publicKey)`

Also, when you export keys, export them as "PEM". So wherever you do `key.export_key()`, it should be `key.export_key("PEM")`.

**Comment by maneeshpm** [comment]
:heavy_check_mark: Changes applied
